CREATE TABLE membro (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50),
	situacao boolean,
	tipo VARCHAR(50),
	sexo VARCHAR(20),
	data_nascimento DATE,
	estado_civil VARCHAR(50),
	cpf VARCHAR(30),
	rg VARCHAR(30),
	nacionalidade VARCHAR(30),
	profissao VARCHAR(50),
	naturalidade VARCHAR(30),
	email VARCHAR(50),
	telefone VARCHAR(30),
	celular VARCHAR(30),
	gra_escolaridade VARCHAR(50),
	curso VARCHAR(40),
	rua VARCHAR(40),
	numero VARCHAR(20),
	bairro VARCHAR(40),
	estado VARCHAR(15),
	cidade VARCHAR(30),
	cep VARCHAR(20),
	nome_pai VARCHAR(50),
	nome_mae VARCHAR(50),
	data_consagracao DATE,
	data_batismo DATE,
	como_se_converteu VARCHAR(50),
	igreja_procedencia VARCHAR(50),
	bastimo_espirito_santo VARCHAR(50),
	dizimista VARCHAR(50),
	observacao VARCHAR(50),
	codigo_tipo_adesao BIGINT(20),
	codigo_situacao_membro BIGINT(20),
	codigo_cargo_ministro BIGINT(20),
	codigo_igreja BIGINT(20),
	FOREIGN KEY (codigo_igreja) REFERENCES igreja(codigo),
	FOREIGN KEY (codigo_situacao_membro) REFERENCES situacao_membro(codigo),
	FOREIGN KEY (codigo_cargo_ministro) REFERENCES cargo_ministro(codigo),
	FOREIGN KEY (codigo_tipo_adesao) REFERENCES tipo_adesao(codigo)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE membro_funcoes (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	codigo_membro BIGINT(20),
	codigo_funcao BIGINT(20),
	FOREIGN KEY (codigo_membro) REFERENCES membro(codigo),
	FOREIGN KEY (codigo_funcao) REFERENCES funcao_membro(codigo)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


